default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

-   repo: https://github.com/golangci/golangci-lint
    rev: v2.2.2
    hooks:
    -   id: golangci-lint-fmt
    -   id: golangci-lint-full
